Feat/dv360 reader
artefactory/nautilus-connectors-kit pull request #40
Opened 2020-08-13 12:03 UTC by Haypierre

Make sure you have checked _all_ steps below.

### Issue

- [ ] My PR addresses the following Issue (If an issue exists in JIRA or Github)

### Description

- [ ] Here are some details about my PR, including example of usage.

### Tests

- [ *] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ *] I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

2020-08-19 15:36 UTC, benoitgoujon reviewed
Bien joué pour ce nouveau connecteur. Globalement pas grand chose à dire pour cette première review. Le code est clair et bien découpé 👍

2020-08-19 15:36 UTC, benoitgoujon commented on nck/readers/dv360_reader.py
> +        return self.kwargs.get("advertiser_id")
Je pense que tu as fait ça pour plus de clarté mais pourquoi ne pas en faire des attributs de la classe directement ?

2020-08-19 15:36 UTC, benoitgoujon commented on nck/readers/dv360_reader.py
> +            raise Exception("The operation has exceed the time limit treshold.\n")
Bonne idée de lever des exceptions ici mais j'aurais créé une exception custom avec un nom bien explicite qui hérite de cette classe. Toujours une bonne pratique d'être spécifique 🙂

2020-08-19 15:36 UTC, benoitgoujon commented on nck/readers/dv360_reader.py
> +            raise Exception("The operation finished in error with code %s: %s" % (
Pareil. On voit bien que les deux exceptions sont différentes donc il faut bien les différencier.

2020-08-19 15:36 UTC, benoitgoujon commented on nck/readers/dv360_reader.py
> +            logging.info(f"Download {int(status.progress() * 100)}.")
Excellente idée le log avec le statut mais j'ai l'impression qu'il manque quelque chose dans le message. C'est un % non ? Qu'est-ce que tu penses de "Download progress: n %"

2020-08-19 15:36 UTC, benoitgoujon commented on nck/readers/dv360_reader.py
> +                yield line
Dans les autres connecteurs, il me semble qu'on mettait le parsing dans un autre fichier pour pouvoir réutiliser les méthodes. Notamment dans `nck/utils/text.py` (qu'on pourrait renommer d'ailleurs). L'idée serait de faire des méthodes très génériques qu'on puisse réutiliser entre readers.

2020-08-19 15:36 UTC, benoitgoujon commented on nck/readers/dv360_reader.py
> +        return body
J'aurais été au plus simple.

```python
    def get_sdf_body(self):
        return {
            "parentEntityFilter": {
                "fileType": self.file_type,
                "filterType": self.filter_type
            },
            "version": self.SDF_VERSION,
            "advertiserId": self.advertiser_id
        }
```

C'est aussi clair je trouve.

2020-08-19 15:36 UTC, benoitgoujon commented on nck/readers/dv360_reader.py
> +        created_operation = self._wait_sdf_download_request(init_operation)
Ici on ne fait rien de l'exception du coup ?

2020-08-19 15:36 UTC, benoitgoujon commented on nck/utils/file_reader.py
> +        zip_ref.extractall(output_path)
👍

2020-08-19 15:36 UTC, benoitgoujon commented on nck/readers/dv360_reader.py
> +        stop=stop_after_delay(36000),
Comment as-tu fixé ce temps ? Je pose la question car le temps du job, c'est de l'occupation de ressources sur notre cluster donc autant libérer rapidement si on voit que ça mène à rien.

2020-08-24 08:48 UTC, aderennes requested changes
Bonne première PR ! Il y a quelques petites choses à modifier et des tests à ajouter mais on est globalement bon.

2020-08-24 08:48 UTC, aderennes commented on nck/readers/dv360_reader.py
> +        #             Required: One can provide several file types.
à mettre en docstring si jamais on génère un readthedocs de ce truc :)

2020-08-24 08:48 UTC, aderennes commented on nck/readers/dv360_reader.py
> +        #               Required: Only one filter_type allowed.
idem

2020-08-24 08:48 UTC, aderennes commented on nck/readers/dv360_reader.py
> +        # map file_type with the name of the generated file.
idem

2020-08-24 08:48 UTC, aderennes commented on nck/readers/dv360_reader.py
> +    # make sure to implement the appropriate retry policy.
à supprimer

2020-08-24 08:48 UTC, aderennes commented on nck/readers/dv360_reader.py
> +        stop=stop_after_delay(36000),
j'ai l'impression que c'est juste ce qui a été mis par défaut sur tous les connecteurs - @bibimorlet c'était arbitraire ?
dans notre cas on pourrait être plus malin car on sait combien de temps il nous faut à peu près pour générer le lien de download, mais a priori si ça marchait pour les autres connecteurs, ça marchera là

2020-08-24 08:48 UTC, aderennes commented on nck/readers/dv360_reader.py
> +            logging.info(f"Download {int(status.progress() * 100)}.")
non c'est une f string, c'est juste que les formats des logs sont pas cohérents d'un log à l'autre

2020-08-24 08:48 UTC, aderennes commented on nck/readers/dv360_reader.py
> +        self.download_sdf(created_operation)
on peut enlever les commentaires, on comprend bien ce qu'il se passe avec le nom des méthodes

2020-08-24 08:48 UTC, aderennes commented on tests/readers/test_dv360_reader.py
> +class TestDV360Reader(TestCase):
c'est un bon début, maintenant il faudrait tester que le code lève bien les bonnes exceptions quand on reçoit les certains payloads puisque la mécanique du connecteur se repose beaucoup sur les exceptions, ce n'est pas forcément la peine de tester les retries et les appels API

2020-08-24 08:51 UTC, benoitgoujon commented on nck/readers/dv360_reader.py
> +            logging.info(f"Download {int(status.progress() * 100)}.")
Oui oui mais là on va avoir un log du type "Dowload 57." Ce qui n'est pas hyper explicite ...

2020-08-24 08:53 UTC, aderennes commented on nck/readers/dv360_reader.py
> +            logging.info(f"Download {int(status.progress() * 100)}.")
ok on oublie mon commentaire d'avant, je suis pas encore réveillé

2020-08-25 16:28 UTC, merged